[project]
name = "SamApp2024Py"
version = "0.1.0"
description = "Add a short description here"
authors = ["Jorge FdCD <jfdecd@icloud.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.12.4,<3.13"
numpy = ">=2.0.1,<2.1"
matplotlib = ">=3.9.1,<3.10"
numba = ">=0.60.0,<0.61"
ipykernel = ">=6.29.5,<6.30"
scipy = ">=1.14.0,<1.15"
